### ISSUE TITLE
What's the roadmap for Windows support?

### ISSUE THREAD

**Issue by cjcjameson** [opendistro/for-elasticsearch#72]
Hi there! Using this ODfE is attractive because in our current deployments, we use open-source Elasticsearch + open-source SearchGuard. We ship "hosted" SaaS software, using AWS's Elasticsearch service, as well as selling an "on-premises" software bundle, so ODfE could put us closer in-parity across the two stacks.

However, we need to support Windows for "on-premises" deployments; is there a roadmap for https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/ becoming more-strongly recommended?

**Comment by aetter** [comment]
Hi @cjcjameson, thanks for reaching out. Historically, we haven't seen much interest in running the Windows version on a server, so it hasn't been an area of huge investment for us. The Windows version tends to appeal to people who run Windows locally and want a development environment sans Docker or the Windows subsystem for Linux.

That said, I don't see any particular reason why the Windows version would be significantly buggier, less stable, or slower. It's not covered in our docs, because I haven't personally done it, but my understanding is that you can install Elasticsearch as a Windows service so that it a) runs in the background b) runs automatically on Windows startup/through reboots and c) is a little easier to monitor. First, set JAVA_HOME. Then run:

```
.\bin\elasticsearch-service.bat install
.\bin\elasticsearch-service.bat start
```

Having Elasticsearch operate as a Windows service should put you almost on-par with the Debian or RPM installs in terms of convenience, though upgrading will be more challenging. Just be sure to take a safety snapshot (which is best practice, anyway) and preserve the `data` and `config` directories.

I've opened a bug in the docs to try and cover this use case in greater detail: https://github.com/opendistro/for-elasticsearch-docs/issues/269

If you're able to get the Windows install working to your satisfaction in an on-premises cluster, please let me know the steps you took so that we can consider incorporating them into the docs. Thanks!
